controllersV1:
    resource: ../../src/Controller/V1/
    type: annotation
    prefix: /v1
    name_prefix: v1.
    trailing_slash_on_root: true
    defaults:
        _format: json

kernel:
    resource: ../../src/Kernel.php
    type: annotation
